// Copyright (c) 2023 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ai.observe;

import ballerina/cache;
import ballerina/io;
import ballerina/log;
import ballerina/time;
import ballerina/uuid;

# Execution progress record
type ExecutionProgress record {|
    # Unique identifier for this execution
    string executionId;
    # Question to the agent
    string query;
    # Instruction used by the agent during the execution
    string instruction;
    # Execution history of actions performed so far in the current interaction
    ExecutionStep[] executionSteps = [];
    # Contextual information to be used by the tools during the execution
    Context context;
    # History of previous interactions with the agent, including the latest user query
    ChatMessage[] history;
|};

# Execution step information
public type ExecutionStep record {|
    # Response generated by the LLM
    json|FunctionCall llmResponse;
    # Observations produced by the tool during the execution
    anydata|error observation;
|};

# Execution step information
public type ExecutionResult record {|
    # Tool decided by the LLM during the reasoning
    LlmToolResponse tool;
    # Observations produced by the tool during the execution
    anydata|error observation;
|};

public type ExecutionError record {|
    # Response generated by the LLM
    json llmResponse;
    # Error caused during the execution
    LlmInvalidGenerationError|ToolExecutionError|MemoryError|UnauthorizedError 'error;
    # Observation on the caused error as additional instruction to the LLM
    string observation;
|};

# An chat response by the LLM
type LlmChatResponse record {|
    # A text response to the question
    string content;
|};

# Tool selected by LLM to be performed by the agent
public type LlmToolResponse record {|
    # Name of the tool to selected
    string name;
    # Input to the tool
    map<json>? arguments = {};
    # Identifier for the tool call
    string id?;
|};

# Output from executing an action
public type ToolOutput record {|
    # Output value the tool
    anydata|error value;
|};

type BaseAgent distinct isolated object {
    ModelProvider model;
    ToolStore toolStore;
    Memory memory;
    boolean stateless;
    cache:Cache tokenManager;
    Credential? agentCredential;

    # Parse the llm response and extract the tool to be executed.
    #
    # + llmResponse - Raw LLM response
    # + return - A record containing the tool decided by the LLM, chat response or an error if the response is invalid
    isolated function parseLlmResponse(json llmResponse) returns LlmToolResponse|LlmChatResponse|LlmInvalidGenerationError;

    # Use LLM to decide the next tool/step.
    #
    # + progress - Execution progress with the current query and execution history
    # + sessionId - The ID associated with the agent memory
    # + return - LLM response containing the tool or chat response (or an error if the call fails)
    isolated function selectNextTool(ExecutionProgress progress, string sessionId = DEFAULT_SESSION_ID) returns json|Error;

    isolated function run(string query, string instruction, int maxIter = 5, boolean verbose = true,
            string sessionId = DEFAULT_SESSION_ID, Context context = new, string executionId = DEFAULT_EXECUTION_ID)
            returns ExecutionTrace;
};

# An executor to perform step-by-step execution of the agent.
class Executor {
    *object:Iterable;
    private boolean isCompleted = false;
    # Set when a tool requests human input, signalling the loop to pause.
    public boolean isInterrupted = false;
    # The human-input request and the tool call that triggered the pause.
    public Interrupted? interrupt = ();
    private final string sessionId;
    private final BaseAgent agent;
    # Contains the current execution progress for the agent and the query
    public ExecutionProgress progress;
    private string? agentId = ();

    # Initialize the executor with the agent and the query.
    #
    # + agent - Agent instance to be executed
    # + query - Natural language query to be executed by the agent
    # + history - Execution history of the agent (This is used to continue an execution paused without completing)
    # + context - Contextual information to be used by the tools during the execution
    isolated function init(BaseAgent agent, string sessionId, *ExecutionProgress progress) {
        self.sessionId = sessionId;
        self.agent = agent;
        self.progress = progress;
        Credential? agentCredential = agent.agentCredential;
        if agentCredential is Credential {
            self.agentId = agentCredential.id;
        }
    }

    # Checks whether agent has more steps to execute.
    #
    # + return - True if agent has more steps to execute, false otherwise
    public isolated function hasNext() returns boolean {
        return !self.isCompleted && !self.isInterrupted;
    }

    # Reason the next step of the agent.
    #
    # + return - generated LLM response during the reasoning or an error if the reasoning fails
    public isolated function reason() returns json|Error {
        if self.isCompleted {
            log:printError("Task is already completed. No more reasoning is needed.",
                agentId = self.agentId,
                executionId = self.progress.executionId
            );
            return error TaskCompletedError("Task is already completed. No more reasoning is needed.");
        }
        log:printDebug("LLM reasoning started",
            agentId = self.agentId,
            executionId = self.progress.executionId,
            sessionId = self.sessionId,
            history = self.progress.executionSteps.toString()
        );
        return check self.agent.selectNextTool(self.progress, self.sessionId);
    }

    # Execute the next step of the agent.
    #
    # + llmResponse - LLM response containing the tool to be executed and the raw LLM output
    # + return - Observations from the tool can be any|error|null
    public isolated function act(json llmResponse) returns ExecutionResult|LlmChatResponse|ExecutionError|Interrupted {
        LlmToolResponse|LlmChatResponse|LlmInvalidGenerationError parsedOutput = self.agent.parseLlmResponse(llmResponse);
        if parsedOutput is LlmChatResponse {
            log:printDebug("Parsed LLM response as chat response",
                agentId = self.agentId,
                executionId = self.progress.executionId,
                sessionId = self.sessionId,
                response = parsedOutput.content
            );
            self.isCompleted = true;
            return parsedOutput;
        }

        anydata observation;
        ExecutionResult|ExecutionError executionResult;
        if parsedOutput is LlmToolResponse {
            string toolName = parsedOutput.name;
            log:printDebug("Parsed LLM response as tool call",
                agentId = self.agentId,
                executionId = self.progress.executionId,
                sessionId = self.sessionId,
                toolName = toolName,
                arguments = parsedOutput.arguments
            );
            observe:ExecuteToolSpan span = observe:createExecuteToolSpan(toolName);
            string? toolCallId = parsedOutput.id;
            if toolCallId is string {
                span.addId(toolCallId);
            }
            ToolStore toolStore = self.agent.toolStore;
            string? toolDescription = toolStore.getToolDescription(toolName);
            if toolDescription is string {
                span.addDescription(toolDescription);
            }
            boolean isMcpTool = toolStore.isMcpTool(toolName);
            span.addType(isMcpTool ? observe:EXTENTION : observe:FUNCTION);
            span.addArguments(parsedOutput.arguments);
            ToolNotFoundError|ToolInvalidInputError|TokenAcquisitionError|TokenValidationError? 
                    validateRes = validateTool(parsedOutput, self.agent.agentCredential, 
                    self.agent.tokenManager, self.progress.context, toolStore.tools, isMcpTool);
            if validateRes is Error {
                log:printError("Tool validation failed",
                    agentId = self.agentId,
                    executionId = self.progress.executionId,
                    sessionId = self.sessionId,
                    toolName = toolName,
                    'error = validateRes
                );
                if validateRes is ToolNotFoundError|ToolInvalidInputError {
                    observation = "Tool extraction failed due to tool validation"; 
                    executionResult = {
                        llmResponse,
                        'error: validateRes,
                        observation: observation.toString()
                    };
                    Error toolExecutionError = error Error(observation.toString(), details = {parsedOutput});
                    span.close(toolExecutionError); 
                } else {
                    observation = "Tool execution failed while attempting to execute the selected tool: "
                        + validateRes.message();
                    executionResult = {
                        llmResponse,
                        'error: error UnauthorizedError (
                            string `Tool execution failed: ${validateRes.message()}`, 
                            details = { parsedOutput }, cause = validateRes.cause(), toolName= toolName),
                        observation: observation.toString()
                    };
                    UnauthorizedError toolExecutionError = error UnauthorizedError(observation.toString(), 
                        details = {parsedOutput});
                    span.close(toolExecutionError); 
                }
            } else {
                ToolOutput|ToolExecutionError|LlmInvalidGenerationError output = toolStore.execute(parsedOutput,
                    self.progress.context);
                if output is Error {
                    if output is ToolNotFoundError {
                        observation = "Tool is not found. Please check the tool name and retry.";
                    } else if output is ToolInvalidInputError {
                        observation = "Tool execution failed due to invalid inputs. Retry with correct inputs.";
                    } else {
                        observation = "Tool execution failed. Retry with correct inputs.";
                    }
                    observation = string `${observation.toString()} <detail>${output.toString()}</detail>`;
                    executionResult = {
                        llmResponse,
                        'error: output,
                        observation: observation.toString()
                    };
                    log:printError("Tool execution resulted in error",
                        agentId = self.agentId,
                        executionId = self.progress.executionId,
                        observation = observation.toString(),
                        sessionId = self.sessionId,
                        toolName = toolName
                    );

                    Error toolExecutionError = error Error(observation.toString(), details = {parsedOutput});
                    span.close(toolExecutionError);
                } else {
                    anydata|error value = output.value;
                    if value is HumanInput {
                        log:printDebug("Tool requested human input; pausing the agent",
                            agentId = self.agentId,
                            executionId = self.progress.executionId,
                            sessionId = self.sessionId,
                            toolName = toolName,
                            requestMessage = value.message
                        );
                        self.isInterrupted = true;
                        Interrupted interrupted = {request: value, pendingCall: parsedOutput};
                        self.interrupt = interrupted;
                        span.addOutput(value.message);
                        span.close();
                        // Do not record an execution step: the tool call is left "dangling"
                        // (no observation) so it becomes the resume checkpoint.
                        return interrupted;
                    }
                    observation = value is error ? value.toString() : value;
                    log:printDebug("Tool execution successful",
                        agentId = self.agentId,
                        executionId = self.progress.executionId,
                        sessionId = self.sessionId,
                        toolName = toolName
                    );
                    executionResult = {
                        tool: parsedOutput,
                        observation: value
                    };

                    span.addOutput(observation);
                    span.close();
                }
            }
        } else {
            log:printDebug("Failed to parse LLM response as valid tool or chat",
                agentId = self.agentId,
                executionId = self.progress.executionId,
                sessionId = self.sessionId,
                errorMessage = parsedOutput.message()
            );
            observation = "Tool extraction failed due to invalid JSON_BLOB. Retry with correct JSON_BLOB.";
            executionResult = {
                llmResponse,
                'error: parsedOutput,
                observation: observation.toString()
            };
        }
        self.update({
            llmResponse,
            observation
        });
        return executionResult;
    }

    # Update the agent with an execution step.
    #
    # + step - Latest step to be added to the history
    public isolated function update(ExecutionStep step) {
        self.progress.executionSteps.push(step);
    }

    # Iterate over the agent's execution steps.
    #
    # + return - a record with the execution step or an error if the agent failed
    public function iterator() returns object {
        public function next() returns record {|ExecutionResult|LlmChatResponse|ExecutionError|Interrupted|Error value;|}?;
    } {
        return self;
    }

    # Reason and execute the next step of the agent.
    #
    # + return - A record with ExecutionResult, chat response, an interrupt or an error
    public isolated function next() returns record {|ExecutionResult|LlmChatResponse|ExecutionError|Interrupted|Error value;|}? {
        if self.isCompleted || self.isInterrupted {
            return ();
        }
        json|Error llmResponse = self.reason();
        if llmResponse is Error {
            return {value: llmResponse};
        }
        return {value: self.act(llmResponse)};
    }
}

# Execute the agent for a given user's query.
#
# + agent - Agent to be executed
# + instruction - Instruction that the agent uses to execute the task
# + query - Natural langauge commands to the agent  
# + maxIter - No. of max iterations that agent will run to execute the task (default: 5)
# + context - Context values to be used by the agent to execute the task
# + verbose - If true, then print the reasoning steps (default: true)
# + agentId - Optional agent identifier used for logging
# + sessionId - The ID associated with the memory
# + executionId - Unique identifier for this execution
# + return - Returns the execution steps tracing the agent's reasoning and outputs from the tools
isolated function run(BaseAgent agent, string instruction, string query, int maxIter, boolean verbose, string? agentId, 
        string sessionId = DEFAULT_SESSION_ID, Context context = new, string executionId = DEFAULT_EXECUTION_ID)
        returns ExecutionTrace {
    log:printDebug("Agent execution loop started",
        agentId = agentId,
        executionId = executionId,
        sessionId = sessionId,
        maxIterations = maxIter,
        tools = agent.toolStore.tools.toString(),
        isStateless = agent.stateless
    );

    // Retrieve the conversation history from memory, update the system message at the start,
    // and append the user message for the current interaction.
    // After iterating and collecting execution steps in temporary memory,
    // update the actual memory in a single batch, including the system prompt and user message for this interaction.
    ChatMessage[]|MemoryError prevHistory = agent.memory.get(sessionId);
    if prevHistory is MemoryError {
        log:printDebug("Failed to retrieve conversation history from memory",
                prevHistory,
                agentId = agentId,
                executionId = executionId,
                sessionId = sessionId
        );
    }
    ChatMessage[] history = (prevHistory is ChatMessage[]) ? [...prevHistory] : [];
    ChatSystemMessage systemMessage = {role: SYSTEM, content: instruction};
    if history.length() > 0 {
        ChatMessage firstMessage = history[0];
        if firstMessage is ChatSystemMessage && instruction != toString(firstMessage.content) {
            history[0] = systemMessage;
        }
    } else {
        history.unshift(systemMessage);
    }
    ChatUserMessage userMessage = {role: USER, content: query};
    history.push(userMessage);

    Executor executor = new (agent, sessionId, progress = {instruction, query, context, executionId, history});
    ChatMessage[] temporaryMemory = [systemMessage, userMessage];
    return executeLoop(agent, executor, history, temporaryMemory, maxIter, verbose, sessionId, agentId, executionId);
}

# Drives the reason-act iteration of the agent until it produces a final answer, errors,
# reaches `maxIter`, or pauses for human input. Shared by `run` (initial query) and
# `resumeRun` (continuation after a human response).
#
# + agent - Agent being executed
# + executor - Pre-initialized executor holding the seeded execution progress
# + history - Conversation history up to (and including) the current turn's trigger message
# + temporaryMemory - Messages to persist for this turn, pre-seeded by the caller
# + maxIter - Maximum number of iterations for this segment of execution
# + verbose - If true, prints the reasoning steps
# + sessionId - The ID associated with the memory
# + agentId - Optional agent identifier used for logging
# + executionId - Unique identifier for this execution
# + return - Returns the execution trace, carrying an `Interrupt` when paused for human input
isolated function executeLoop(BaseAgent agent, Executor executor, ChatMessage[] history,
        ChatMessage[] temporaryMemory, int maxIter, boolean verbose, string sessionId,
        string? agentId, string executionId) returns ExecutionTrace {
    time:Utc startTime = time:utcNow();
    Iteration[] iterations = [];
    (ExecutionResult|ExecutionError|Error)[] steps = [];
    string? content = ();
    ChatAssistantMessage? finalAssistantMessage = ();
    int iter = 0;
    foreach ExecutionResult|LlmChatResponse|ExecutionError|Interrupted|Error step in executor {
        ChatAssistantMessage|ChatFunctionMessage|Error iterationOutput = getOutputOfIteration(step);
        ChatMessage[] iterationHistory = buildCurrentIterationHistory(executor.progress, history);
        if verbose {
            verbosePrint(step, iter);
        }
        if step is Interrupted {
            // A tool requested human input. Persist the conversation so far, leaving the
            // triggering tool call "dangling" (no result) as the resume checkpoint, and
            // surface an `Interrupt` to the caller. Memory is NOT deleted for stateless
            // agents while paused, otherwise the checkpoint would be lost before resume.
            ChatAssistantMessage danglingAssistant = buildDanglingAssistant(step.pendingCall);
            iterations.push({startTime, endTime: time:utcNow(), history: iterationHistory,
                    output: danglingAssistant});
            temporaryMemory.push(...createFunctionCallMessages(executor.progress));
            temporaryMemory.push(danglingAssistant);
            updateMemory(agent.memory, sessionId, temporaryMemory, agentId);
            Interrupt interrupt = buildInterrupt(sessionId, step);
            log:printDebug("Agent paused awaiting human input",
                agentId = agentId,
                executionId = executionId,
                sessionId = sessionId,
                toolName = interrupt.toolName,
                interruptId = interrupt.interruptId
            );
            return {steps, iterations, answer: (), toolCalls: collectToolCalls(executor.progress), interrupt};
        }
        if iter == maxIter {
            log:printDebug("Maximum iterations reached without final answer",
                agentId = agentId,
                executionId = executionId,
                iterations = iter,
                stepsCompleted = steps.length(),
                sessionId = sessionId
            );
            break;
        }
        if step is ExecutionError && step.'error is UnauthorizedError {
            error err = step.'error;
            content = "I could not complete your request due to an authorization issue, " +
              "possibly related to the access token or its permissions. Please check that your "
              + "credentials are valid and have the required access, then try again";
            Error newError =  error Error(content.toString(), 'error = err);
            iterationOutput = newError;
            if verbose {
                verbosePrint(newError, iter);
            }
            log:printDebug("Tool execution failed: ",
                err,
                executionId = executionId,
                iteration = iter,
                sessionId = sessionId
            );
            steps.push(step);
            finalAssistantMessage = {role: ASSISTANT, content: content};
            iterations.push({startTime, endTime: time:utcNow(), history: iterationHistory, output: iterationOutput});
            break;
        }
        if step is Error {
            error? cause = step.cause();
            log:printDebug("Error occurred during agent iteration",
                    step,
                    executionId = executionId,
                    iteration = iter,
                    sessionId = sessionId,
                    cause = cause !is () ? cause.toString() : "none"
                );
            steps.push(step);
            iterations.push({startTime, endTime: time:utcNow(), history: iterationHistory, output: iterationOutput});
            break;
        }
        if step is LlmChatResponse {
            content = step.content;
            log:printDebug("Final answer generated by agent",
                agentId = agentId,
                executionId = executionId,
                iteration = iter,
                answer = content,
                sessionId = sessionId
            );
            finalAssistantMessage = {role: ASSISTANT, content: content};
            iterations.push({startTime, endTime: time:utcNow(), history: iterationHistory, output: iterationOutput});
            break;
        }
        iter += 1;
        log:printDebug("Agent iteration started",
            agentId = agentId,
            executionId = executionId,
            iteration = iter,
            maxIterations = maxIter,
            stepsCompleted = steps.length(),
            sessionId = sessionId
        );
        steps.push(step);
        iterations.push({startTime, endTime: time:utcNow(), history: iterationHistory, output: iterationOutput});
        startTime = time:utcNow();
    }

    ChatMessage[] intermediateFunctionCallMessages = createFunctionCallMessages(executor.progress);
    temporaryMemory.push(...intermediateFunctionCallMessages);
    if finalAssistantMessage is ChatAssistantMessage {
        temporaryMemory.push(finalAssistantMessage);
    }

    // Batch update the memory with the user message, system message, and all intermediate steps from tool execution
    updateMemory(agent.memory, sessionId, temporaryMemory, agentId);
    if agent.stateless {
        MemoryError? err = agent.memory.delete(sessionId);
        // Ignore this error since the stateless agent always relies on DefaultMessageWindowChatMemoryManager,
        // which never return an error.
    }
    return {steps, iterations, answer: content, toolCalls: collectToolCalls(executor.progress)};
}

# Builds the assistant message representing a tool call whose result is not yet available
# (the resume checkpoint persisted to memory when the agent pauses for human input).
#
# + tool - The tool call that triggered the pause
# + return - An assistant message carrying the single dangling tool call
isolated function buildDanglingAssistant(LlmToolResponse tool) returns ChatAssistantMessage {
    FunctionCall functionCall = {name: tool.name, arguments: tool.arguments};
    string? id = tool.id;
    if id is string {
        functionCall.id = id;
    }
    return {role: ASSISTANT, toolCalls: [functionCall]};
}

# Builds the `Interrupt` surfaced to the caller from a tool's human-input request.
#
# + sessionId - The session the paused execution belongs to
# + interrupted - The human-input request and the triggering tool call
# + return - The interrupt describing what the human must provide
isolated function buildInterrupt(string sessionId, Interrupted interrupted) returns Interrupt {
    HumanInput request = interrupted.request;
    LlmToolResponse tool = interrupted.pendingCall;
    Interrupt interrupt = {
        interruptId: uuid:createRandomUuid(),
        sessionId,
        toolName: tool.name,
        toolArguments: tool.arguments,
        message: request.message
    };
    map<json>? responseSchema = request?.responseSchema;
    if responseSchema is map<json> {
        interrupt.responseSchema = responseSchema;
    }
    map<json>? metadata = request?.metadata;
    if metadata is map<json> {
        interrupt.metadata = metadata;
    }
    return interrupt;
}

# Collects the tool calls performed across the execution steps.
#
# + progress - The execution progress holding the recorded steps
# + return - The function calls issued by the agent during this execution
isolated function collectToolCalls(ExecutionProgress progress) returns FunctionCall[] =>
    from ExecutionStep step in progress.executionSteps
    let var llmResponse = step.llmResponse
    where llmResponse is FunctionCall
    select llmResponse;

# Resumes a paused agent execution by injecting the human's response as the result of the
# tool call that triggered the pause, then continuing the reason-act loop.
#
# + agent - Agent to be resumed
# + instruction - Instruction that the agent uses to execute the task
# + response - The human's response, injected as the paused tool call's result
# + maxIter - No. of max iterations for the resumed segment of execution
# + context - Context values to be used by the agent to execute the task
# + verbose - If true, then print the reasoning steps
# + agentId - Optional agent identifier used for logging
# + sessionId - The ID associated with the memory holding the pending interrupt
# + executionId - Unique identifier for this execution
# + return - The execution trace, or a `NoPendingInterruptError` if nothing is paused
isolated function resumeRun(BaseAgent agent, string instruction, HumanResponse response, int maxIter,
        boolean verbose, string? agentId, string sessionId = DEFAULT_SESSION_ID, Context context = new,
        string executionId = DEFAULT_EXECUTION_ID) returns ExecutionTrace|Error {
    log:printDebug("Agent resume loop started",
        agentId = agentId,
        executionId = executionId,
        sessionId = sessionId,
        maxIterations = maxIter
    );

    ChatMessage[]|MemoryError prevHistory = agent.memory.get(sessionId);
    if prevHistory !is ChatMessage[] || prevHistory.length() == 0 {
        return error NoPendingInterruptError(
            "No paused execution found for the session to resume.", sessionId = sessionId);
    }
    ChatMessage[] history = [...prevHistory];

    // The trailing interactive message must be an assistant message carrying a tool call
    // whose result is not yet recorded (the dangling checkpoint persisted at pause time).
    ChatMessage lastMessage = history[history.length() - 1];
    if lastMessage !is ChatAssistantMessage {
        return error NoPendingInterruptError(
            "No pending human-input interrupt found for the session to resume.", sessionId = sessionId);
    }
    FunctionCall[]? pendingToolCalls = lastMessage.toolCalls;
    if pendingToolCalls is () || pendingToolCalls.length() == 0 {
        return error NoPendingInterruptError(
            "No pending human-input interrupt found for the session to resume.", sessionId = sessionId);
    }
    FunctionCall pendingCall = pendingToolCalls[0];

    // Keep the system message aligned with the current instruction.
    ChatMessage firstMessage = history[0];
    if firstMessage is ChatSystemMessage && instruction != toString(firstMessage.content) {
        history[0] = <ChatSystemMessage>{role: SYSTEM, content: instruction};
    }

    // Inject the human response as the result of the paused tool call.
    string responseText = humanResponseToString(response);
    ChatFunctionMessage humanResultMessage = {role: FUNCTION, name: pendingCall.name, content: responseText};
    string? id = pendingCall.id;
    if id is string {
        humanResultMessage.id = id;
    }
    history.push(humanResultMessage);

    // The system, user, completed steps, and the dangling assistant message are already
    // persisted. Only the injected human result and subsequent steps/answer are new.
    ChatMessage[] temporaryMemory = [humanResultMessage];
    Executor executor = new (agent, sessionId,
        progress = {instruction, query: responseText, context, executionId, history});
    return executeLoop(agent, executor, history, temporaryMemory, maxIter, verbose, sessionId, agentId, executionId);
}

# Serializes a human response into the string content of a function-result chat message.
#
# + response - The human's response value
# + return - The string representation injected back into the conversation
isolated function humanResponseToString(HumanResponse response) returns string {
    if response is string {
        return response;
    }
    return response.toJsonString();
}

isolated function verbosePrint(ExecutionResult|LlmChatResponse|ExecutionError|Interrupted|Error step, int iter) {
    io:println(string `${"\n\n"}Agent Iteration ${iter.toString()}`);
    if step is LlmChatResponse {
        io:println(string `${"\n\n"}Final Answer: ${step.content}${"\n\n"}`);
        return;
    }
    if step is Interrupted {
        io:println(string `${"\n\n"}Awaiting Human Input: ${step.request.message}${"\n\n"}`);
        return;
    }
    if step is ExecutionResult {
        LlmToolResponse tool = step.tool;
        io:println(string `Action:
    ${BACKTICKS}
    {
        ${ACTION_NAME_KEY}: ${tool.name},
        ${ACTION_ARGUEMENTS_KEY}: ${(tool.arguments ?: "None").toString()}
    }
    ${BACKTICKS}`);

        anydata|error observation = step?.observation;
        if observation is error {
            io:println(string `${OBSERVATION_KEY} (Error): ${observation.toString()}`);
        } else if observation !is () {
            io:println(string `${OBSERVATION_KEY}: ${observation.toString()}`);
        }
        return;
    }
    if step is ExecutionError {
        error? cause = step.'error.cause();
        io:println(string `LLM Generation Error: 
    ${BACKTICKS}
    {
        message: ${step.'error.message()},
        cause: ${(cause is error ? cause.message() : "Unspecified")},
        llmResponse: ${step.llmResponse.toString()}
    }
    ${BACKTICKS}`);
    }
}

isolated function getOutputOfIteration(ExecutionResult|LlmChatResponse|ExecutionError|Interrupted|Error step)
    returns ChatAssistantMessage|ChatFunctionMessage|Error {
    if step is Error {
        return step;
    }
    if step is LlmChatResponse {
        return {role: ASSISTANT, content: step.content};
    }
    if step is ExecutionError {
        return step.'error;
    }
    if step is Interrupted {
        return buildDanglingAssistant(step.pendingCall);
    }
    return {
        role: FUNCTION,
        name: step.tool.name,
        id: step.tool.id,
        content: getObservationString(step.observation)
    };
}

isolated function buildCurrentIterationHistory(ExecutionProgress progress,
        ChatMessage[] conversationHistoryUpToCurrentUserQuery) returns ChatMessage[] {
    ChatMessage[] messages = createFunctionCallMessages(progress);
    messages.unshift(...conversationHistoryUpToCurrentUserQuery);
    return messages;
}

isolated function getObservationString(anydata|error observation) returns string {
    if observation is () {
        return "Tool didn't return anything. Probably it is successful. Should we verify using another tool?";
    } else if observation is error {
        record {|string message; string cause?;|} errorInfo = {
            message: observation.message().trim()
        };
        error? cause = observation.cause();
        if cause is error {
            errorInfo.cause = cause.message().trim();
        }
        return "Error occured while trying to execute the tool: " + errorInfo.toString();
    } else {
        return observation.toString().trim();
    }
}

# Get the tools registered with the agent.
#
# + agent - Agent instance
# + return - Array of tools registered with the agent
public isolated function getTools(Agent agent) returns Tool[] => agent.functionCallAgent.toolStore.tools.toArray();

isolated function updateMemory(Memory memory, string sessionId, ChatMessage[] messages, string? agentId) {
    error? updationStation = memory.update(sessionId, messages);
    if updationStation is error {
        log:printError("Error occured while updating the memory", updationStation, agentId = agentId);
    }
}
